jruby: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-complete-9.1.0.0.jar"
jetty: "file://<%= File.expand_path('spec/local_mirror') %>/jetty-distribution-9.3.8.v20160314.zip"
jruby-rack: "file://<%= File.expand_path('spec/local_mirror') %>/jruby-rack-1.1.20.jar"
http_port: 20080
https_port: 20443
ruby_version: 2.3
app_type: rack
keystore: "etc/fake.p12"
keystore_password: "foobar"
truststore: "etc/fake.p12"
truststore_password: "foobar"
